# Generated by Django 2.2.15 on 2021-09-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0036_ticket_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expected_time',
            field=models.DurationField(blank=True, help_text='Expected time to complete task', null=True),
        ),
    ]
